version: '3'
services:
  server:
    container_name: golang-server
    build: .
    image: golang-server:stable
    environment:
      - HTTP_PORT=3002
    ports:
      - "3002:3002"
    networks:
      - hello-docker
  dapr:
    container_name: golang-server-dapr
    image: "daprio/daprd:edge"
    command: ["./daprd",
      "-app-id", "golang-server",
      "-app-port", "3002",
      "-placement-host-address", "placement:50000",
      "-dapr-grpc-port", "4002",
      "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - server
    network_mode: "service:server"
networks:
  hello-docker:
    external: true
