version: '3'
services:
  app:
    container_name: deno-app
    build: .
    image: deno-app:stable
    environment:
      - HTTP_PORT=3001
    ports:
      - "3001:3001"
    networks:
      - hello-docker
  dapr:
    container_name: deno-dapr
    image: "daprio/daprd:edge"
    command: ["./daprd",
      "-app-id", "deno-app",
      "-app-port", "3001",
      "-placement-host-address", "placement:50000",
      "-dapr-grpc-port", "4001",
      "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - app
    network_mode: "service:app"
networks:
  hello-docker:
    external: true
