version: '3'
services:
  python-app:
    container_name: app
    build: .
    tty: true
    volumes:
      - "./src/:/app"
    networks:
      - hello-docker
networks:
  hello-docker:
    external: true
