version: '3'
services:
  server:
    container_name: node-server
    build: .
    image: node-server:stable
    environment:
      - HTTP_PORT=3000
    ports:
      - "3000:3000"
    networks:
      - hello-docker
  dapr:
    container_name: node-server-dapr
    image: "daprio/daprd:edge"
    command: ["./daprd",
      "-app-id", "node-server",
      "-app-port", "3000",
      "-placement-host-address", "placement:50000",
      "-dapr-grpc-port", "4000",
      "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - server
    network_mode: "service:server"
networks:
  hello-docker:
    external: true
