version: '3'
services:
  server:
    container_name: python-server
    build: .
    image: python-server:stable
    environment:
      - HTTP_PORT=3003
    ports:
      - "3003:3003"
    networks:
      - hello-docker
  dapr:
    container_name: python-server-dapr
    image: "daprio/daprd:edge"
    command: ["./daprd",
      "-app-id", "python-server",
      "-app-port", "3003",
      "-placement-host-address", "placement:50000",
      "-dapr-grpc-port", "4003",
      "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - server
    network_mode: "service:server"
networks:
  hello-docker:
    external: true
