version: '3'
services:
  app:
    container_name: python-app
    build: .
    tty: true
    volumes:
      - "./src/:/app"
    networks:
      - hello-docker
  dapr:
    container_name: python-dapr
    image: "daprio/daprd:edge"
    command: ["./daprd",
      "-app-id", "python-app",
      "-placement-host-address", "placement:50000",
      "-components-path", "/components"]
    depends_on:
      - app
    network_mode: "service:app"
networks:
  hello-docker:
    external: true
